# Generated by Django 3.0.2 on 2020-01-06 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("transaction_date", models.DateField(default=datetime.date.today)),
                ("description", models.CharField(max_length=256)),
                ("amount", models.FloatField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("category", models.CharField(max_length=64)),
                ("sub_categories", models.TextField()),
                (
                    "creation_source",
                    models.CharField(
                        choices=[
                            ("manual", "Created Manually"),
                            ("manual-bank-sync", "Synced from Bank manually"),
                            ("auto-bank-sync", "Synced from Bank automatically"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("is_soft_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
